"use client";

import { useState, useEffect } from "react";
import { LegalAnalysis } from "@/lib/types/legal";
import { TimelineEvent } from "@/lib/types/timeline";
import PageHeader from "@/components/layout/PageHeader";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Printer, Copy, AlertTriangle, CheckSquare } from "lucide-react";
import EmptyState from "@/components/ui/EmptyState";

export default function LawyerBriefPage() {
  const [isMounted, setIsMounted] = useState(false);
  const [analysis, setAnalysis] = useState<LegalAnalysis | null>(null);
  const [timeline, setTimeline] = useState<TimelineEvent[]>([]);
  const [_actionPlan, setActionPlan] = useState<unknown>(null);
  const [desiredOutcome, setDesiredOutcome] = useState("");

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setIsMounted(true);
    
    // Load state from across the application
    const savedAnalysis = localStorage.getItem("nyaya_current_analysis");
    const savedTimeline = localStorage.getItem("nyaya_timeline");
    const savedActionPlan = localStorage.getItem("nyaya_action_plan");
    const savedOutcome = localStorage.getItem("nyaya_desired_outcome");

    if (savedAnalysis) setAnalysis(JSON.parse(savedAnalysis));
    if (savedTimeline) setTimeline(JSON.parse(savedTimeline));
    if (savedActionPlan) setActionPlan(JSON.parse(savedActionPlan));
    if (savedOutcome) setDesiredOutcome(savedOutcome);
  }, []);

  // Save outcome whenever it changes
  useEffect(() => {
    if (isMounted) {
      localStorage.setItem("nyaya_desired_outcome", desiredOutcome);
    }
  }, [desiredOutcome, isMounted]);

  const handlePrint = () => {
    window.print();
  };

  const handleCopy = () => {
    // Basic text dump for copying to clipboard
    const text = `
NyayaAI - Lawyer Brief (AI-Generated Informational Document)
Date: ${new Date().toLocaleDateString()}

60-SECOND SUMMARY:
${analysis?.summary || 'No summary available.'}

KEY FACTS (Provided by user):
${analysis?.knownFacts?.join('\n- ') || 'None provided.'}

DESIRED OUTCOME:
${desiredOutcome || 'Not specified.'}
    `;
    navigator.clipboard.writeText(text.trim());
    alert("Brief copied to clipboard!");
  };

  if (!isMounted) return null;

  return (
    <div className="bg-slate-50 dark:bg-slate-950 min-h-screen pb-12 print:bg-white print:p-0">
      
      {/* Top Navigation / Controls (Hidden on Print) */}
      <div className="container mx-auto px-4 py-8 max-w-4xl print:hidden">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-8">
          <PageHeader 
            title="Lawyer Brief" 
            description="A structured, factual summary of your situation prepared for legal counsel."
            breadcrumb={[{label: 'Home', href: '/'}, {label: 'Lawyer Brief'}]} 
          />
          <div className="flex items-center gap-2">
            <Button variant="outline" onClick={handleCopy} className="bg-white dark:bg-slate-900 border-slate-200">
              <Copy className="w-4 h-4 mr-2" /> Copy
            </Button>
            <Button onClick={handlePrint} className="bg-indigo-600 hover:bg-indigo-700 text-white">
              <Printer className="w-4 h-4 mr-2" /> Print / Save as PDF
            </Button>
          </div>
        </div>

        <Card className="mb-8 border-indigo-100 bg-indigo-50/50 shadow-sm">
          <CardContent className="p-4 flex items-start gap-3">
            <AlertTriangle className="w-5 h-5 text-indigo-600 shrink-0 mt-0.5" />
            <div className="text-sm text-indigo-900 leading-relaxed">
              <strong>Instructions:</strong> Review this document to ensure it accurately reflects your situation. This brief strictly contains information you provided and broad categorizations generated by NyayaAI. It does not contain legal advice or guarantees of success.
            </div>
          </CardContent>
        </Card>
      </div>

      {/* The Printable Brief Document */}
      <div className="container mx-auto max-w-4xl px-4 print:px-0">
        <div className="bg-white dark:bg-slate-900 print:bg-white border border-slate-200 dark:border-slate-800 print:border-none shadow-sm print:shadow-none p-8 md:p-12 rounded-2xl print:p-0 text-slate-800 dark:text-slate-300 print:text-black">
          
          {/* Document Header */}
          <div className="border-b-2 border-slate-900 dark:border-slate-100 print:border-black pb-6 mb-8 flex justify-between items-end">
            <div>
              <h1 className="text-3xl font-bold text-slate-900 dark:text-white print:text-black tracking-tight mb-2">NyayaAI</h1>
              <h2 className="text-xl font-medium text-slate-600 dark:text-slate-400 print:text-gray-700">Client Situation Brief</h2>
            </div>
            <div className="text-right text-sm text-slate-500 print:text-gray-600">
              <p>Generated: {new Date().toLocaleDateString()}</p>
              <p className="font-semibold uppercase tracking-wider mt-1 text-xs">AI-Generated Informational Document</p>
            </div>
          </div>

          {!analysis ? (
            <div className="py-8 print:hidden">
              <EmptyState 
                title="No Brief Available"
                description="Please complete the Assistant flow first so we can gather the necessary facts to generate your brief."
              />
            </div>
          ) : (
            <div className="space-y-10">
              
              {/* Desired Outcome (Interactive Input in App, Static in Print) */}
              <section className="print:break-inside-avoid">
                <h3 className="text-lg font-bold uppercase tracking-wider text-slate-900 dark:text-slate-100 print:text-black mb-4 border-b border-slate-200 print:border-gray-300 pb-2">
                  Desired Outcome
                </h3>
                <div className="print:hidden">
                  <Textarea 
                    placeholder="Briefly describe what you hope to achieve (e.g., 'I want my deposit back', 'I want to resolve this out of court')."
                    value={desiredOutcome}
                    onChange={(e) => setDesiredOutcome(e.target.value)}
                    className="min-h-[100px] text-base"
                  />
                  <p className="text-xs text-slate-500 mt-2">This will be included in the printed document.</p>
                </div>
                <div className="hidden print:block text-base leading-relaxed">
                  {desiredOutcome || "Not specified by user."}
                </div>
              </section>

              <section className="print:break-inside-avoid">
                <h3 className="text-lg font-bold uppercase tracking-wider text-slate-900 dark:text-slate-100 print:text-black mb-4 border-b border-slate-200 print:border-gray-300 pb-2">
                  60-Second Summary
                </h3>
                <p className="text-base leading-relaxed">{analysis.summary}</p>
              </section>

              <section className="print:break-inside-avoid">
                <h3 className="text-lg font-bold uppercase tracking-wider text-slate-900 dark:text-slate-100 print:text-black mb-4 border-b border-slate-200 print:border-gray-300 pb-2 flex justify-between items-baseline">
                  Key Facts
                  <span className="text-xs font-normal text-slate-500 print:text-gray-500">Information provided by the user</span>
                </h3>
                <ul className="list-disc pl-5 space-y-2 text-base">
                  {analysis.knownFacts.map((fact, i) => (
                    <li key={i}>{fact}</li>
                  ))}
                </ul>
              </section>

              <div className="grid md:grid-cols-2 gap-8 print:block print:space-y-10">
                <section className="print:break-inside-avoid">
                  <h3 className="text-lg font-bold uppercase tracking-wider text-slate-900 dark:text-slate-100 print:text-black mb-4 border-b border-slate-200 print:border-gray-300 pb-2">
                    Possible Legal Category
                  </h3>
                  <div className="bg-slate-50 dark:bg-slate-800/50 print:bg-transparent p-4 rounded-lg">
                    <p className="font-semibold text-lg text-slate-900 dark:text-slate-100 print:text-black">{analysis.triageCategory}</p>
                    <p className="text-sm mt-1">{analysis.triageExplanation}</p>
                    {analysis.isEmergency && (
                      <p className="mt-3 text-rose-600 font-bold text-sm uppercase flex items-center gap-1">
                        <AlertTriangle className="w-4 h-4" /> High Risk / Emergency Detected
                      </p>
                    )}
                  </div>
                </section>

                <section className="print:break-inside-avoid">
                  <h3 className="text-lg font-bold uppercase tracking-wider text-slate-900 dark:text-slate-100 print:text-black mb-4 border-b border-slate-200 print:border-gray-300 pb-2">
                    Missing Information
                  </h3>
                  {analysis.missingInformation.length > 0 ? (
                    <ul className="list-disc pl-5 space-y-2 text-base">
                      {analysis.missingInformation.map((info, i) => (
                        <li key={i}>{info}</li>
                      ))}
                    </ul>
                  ) : (
                    <p className="text-slate-500 italic">None identified.</p>
                  )}
                </section>
              </div>

              <section className="print:break-inside-avoid">
                <h3 className="text-lg font-bold uppercase tracking-wider text-slate-900 dark:text-slate-100 print:text-black mb-4 border-b border-slate-200 print:border-gray-300 pb-2">
                  Chronological Timeline
                </h3>
                {timeline.length > 0 ? (
                  <div className="space-y-4">
                    {timeline.map((ev) => (
                      <div key={ev.id} className="flex gap-4 items-start">
                        <div className="w-24 shrink-0 font-semibold text-sm text-slate-900 dark:text-slate-100 print:text-black pt-1">
                          {ev.date}
                        </div>
                        <div>
                          <p className="font-medium text-slate-900 dark:text-slate-100 print:text-black">{ev.title}</p>
                          {ev.description && <p className="text-sm text-slate-600 dark:text-slate-400 print:text-gray-700 mt-1">{ev.description}</p>}
                        </div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <p className="text-slate-500 italic">No timeline events recorded by the user.</p>
                )}
              </section>

              <section className="print:break-inside-avoid">
                <h3 className="text-lg font-bold uppercase tracking-wider text-slate-900 dark:text-slate-100 print:text-black mb-4 border-b border-slate-200 print:border-gray-300 pb-2">
                  Documents Available
                </h3>
                {analysis.documents.length > 0 || timeline.some(e => e.hasDocument) ? (
                  <ul className="list-disc pl-5 space-y-2 text-base">
                    {analysis.documents.map((doc, i) => (
                      <li key={`doc-${i}`}>{doc}</li>
                    ))}
                    {timeline.filter(e => e.hasDocument).map((ev, i) => (
                      <li key={`ev-${i}`}>Document related to: {ev.title} ({ev.date})</li>
                    ))}
                  </ul>
                ) : (
                  <p className="text-slate-500 italic">No documents currently identified.</p>
                )}
              </section>

              <section className="print:break-inside-avoid">
                <h3 className="text-lg font-bold uppercase tracking-wider text-slate-900 dark:text-slate-100 print:text-black mb-4 border-b border-slate-200 print:border-gray-300 pb-2">
                  Questions for the Lawyer
                </h3>
                {/* Fallback questions if specific ones don't exist */}
                <ul className="space-y-3">
                  <li className="flex gap-3">
                    <CheckSquare className="w-5 h-5 shrink-0 text-slate-300 print:text-gray-400 mt-0.5" />
                    <span>What are the potential costs and fee structures for handling this matter?</span>
                  </li>
                  <li className="flex gap-3">
                    <CheckSquare className="w-5 h-5 shrink-0 text-slate-300 print:text-gray-400 mt-0.5" />
                    <span>Are there any immediate deadlines or statutes of limitations I need to worry about?</span>
                  </li>
                  <li className="flex gap-3">
                    <CheckSquare className="w-5 h-5 shrink-0 text-slate-300 print:text-gray-400 mt-0.5" />
                    <span>What are the realistic possible outcomes for my desired resolution?</span>
                  </li>
                </ul>
              </section>

              {/* Print Footer Disclaimer */}
              <div className="mt-16 pt-6 border-t border-slate-200 print:border-gray-300 text-xs text-slate-500 print:text-gray-500 text-center print:break-inside-avoid">
                <strong>Important Legal Notice:</strong> This document was generated by NyayaAI based solely on user-provided inputs. NyayaAI is an AI assistant, not a law firm. This document does not constitute formal legal advice, nor does it form an attorney-client relationship. The language herein explicitly avoids claiming legal validity or guaranteeing outcomes. All factual claims are unverified representations made by the user.
              </div>

            </div>
          )}
        </div>
      </div>
    </div>
  );
}
